worker_processes 1;


events {
   worker_connections 1024;
}


http {
    include mime.types;
	limit_req_zone $binary_remote_addr zone=api_limit:10m rate 10r/s;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate 3r/s;

    
    upstream pulsewatch_api {
        server api:3000; #matches the service name and port of the backend API service defined in the docker-compose.yml file

	}
    server{

    listen 80; #listens on port 80 for incoming HTTP requests because we are using nginx now.
    server_name _; #matches the server_name used in the backend service definition in the docker-compose.yml file

    location / {
        limit_req zone=api_limit burst=20 nodelay; #applies the rate limiting defined in the api_limit zone to this location
        proxy_pass http://pulsewatch_api; #forwards requests to the backend API service defined in the upstream block
        proxy_set_header Host $host; #sends the original host header to the backend
        proxy_set_header X-Real-IP $remote_addr; #sends the client's IP address to the backend
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #sends the client's IP address in the X-Forwarded-For header
        proxy_set_header X-Forwarded-Proto $scheme; #sends the original protocol (http or https) to the backend
    }
    
    location /auth {
            limit_req zone=auth_limit burst=5 nodelay;
            proxy_pass http://pulsewatch_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location /health {
            proxy_pass http://pulsewatch_api;
            proxy_set_header Host $host;
    }


    location /ready {
            proxy_pass http://pulsewatch_api;
            proxy_set_header Host $host;
    }
}}