{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  labels:
    app: pulsewatch
    component: api
    {{- include "pulsewatch.commonLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app: pulsewatch
      component: api
{{- end }}
